name: ledger_cardano
description: A Ledger App Plugin for the Cardano blockchain
version: 1.0.0-pre.1
homepage: https://github.com/RootSoft/ledger-algorand
repository: https://github.com/RootSoft/ledger-algorand
issue_tracker: https://github.com/RootSoft/ledger-algorand/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  # flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  ledger_flutter: ^1.0.0

  algorand_dart: ^2.0.0-dev.4

  freezed_annotation: ^2.4.1 
   
  hex: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
