name: ledger_cardano
description: A Ledger App Plugin for the Cardano blockchain
version: 0.1.0
homepage: https://github.com/vespr-wallet/ledger-cardano
repository: https://github.com/vespr-wallet/ledger-cardano
issue_tracker: https://github.com/vespr-wallet/ledger-cardano/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ledger_flutter:
    git:
      url: https://github.com/vespr-wallet/ledger-flutter
      ref: 97e5b9c84db51e77794f2d7102f037f7ea9bb43e

  freezed_annotation: ^2.4.1
  collection: ^1.18.0
  bech32: ^0.2.2

# dependency_overrides:
#   meta: 1.14.0

dev_dependencies:
  # integration_test:
  #   sdk: flutter
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  build_runner:

flutter:
